-- AlterTable
ALTER TABLE `profiles` MODIFY `name` VARCHAR(191) NULL DEFAULT '',
    MODIFY `cellphone` VARCHAR(191) NULL DEFAULT '',
    MODIFY `avatar` VARCHAR(191) NULL DEFAULT '',
    MODIFY `address` VARCHAR(191) NULL DEFAULT '',
    MODIFY `city` VARCHAR(191) NULL DEFAULT '',
    MODIFY `complement` VARCHAR(191) NULL DEFAULT '',
    MODIFY `neighborhood` VARCHAR(191) NULL DEFAULT '',
    MODIFY `number` VARCHAR(191) NULL DEFAULT '',
    MODIFY `state` VARCHAR(191) NULL DEFAULT '',
    MODIFY `zipcode` VARCHAR(191) NULL DEFAULT '';
